ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Diagrama de despliegue

ifdef::arc42help[]
[role="arc42help"]
****
.Content
The deployment view describes:

 1. technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document a deployment view if your software is executed as distributed system with more than one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture only those elements of an infrastructure that are needed to show a deployment of your building blocks. Hardware architects can go beyond that and describe an infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence a system and/or some
cross-cutting concepts. Therefore, there is a need to know the infrastructure.

.Form

Maybe a highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section one can
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than a deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.


.Further Information

See https://docs.arc42.org/section-7/[Deployment View] in the arc42 documentation.

****
endif::arc42help[]

Para representar de la manera más exacta y representativa posible el despliegue de nuestro sistema en la máquina virtual creada para la realización de las prácticas, se especifican dos niveles de infraestructura, 
con el fin ofrecer distintos puntos de vista del sistema: uno más general que represente los módulos más característicos de nuestro sistema, y otro más específico en el que aparecen los distintos contenedores encargados
de la monitorización del mismo.

=== Nivel de infraestructura 1

ifdef::arc42help[]
[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****
endif::arc42help[]

[plantuml,"Diagrama de despliegue",png]
----
@startuml
skinparam monochrome true
left to right direction

node "Navegador" <<device>> as Navegador

node "Azure VM (Linux Ubuntu 24.04)" <<device>> as AzureVM {

    node "Docker" <<execution environment>> as Docker {
        artifact "WebApp\n(React Front-end)"   as WebApp
        artifact "Users\n(Node Back-end)"      as Users
        artifact "Gamey\n(Rust Game Engine)"   as Gamey
        
        node "Database" as Database{
            artifact "MySQL"                   as MySQL
            artifact "db_data"                 as Volume <<volume>>
        }
    }
}

Navegador   --   WebApp      : <<interaccón UI>>
WebApp      -->  Users       : <<HTTP/REST>>
WebApp      -->  Gamey       : <<HTTP/REST>>
Users       --   MySQL       : <<MySQL>>
MySQL       --   Volume      : <<mount>>

@enduml
----

Descripción::

La aplicación se despliega sobre un servidor de Azure, en el que cada módulo que constituye el sistema se encuentra encapsulado en un contenedor de Docker. 
+
El usuario interactua con el sistema a través del módulo WebApp, que no es más que una interfaz gráfica diseñada en React. El front-end a su vez se comunica con los dos back-ends del sistema mediante peticiones HTTP: Users y Gamey. 
Cada uno de ellos expone una serie de endpoints para realizar diferentes tareas, ya sea consultar la base de datos y almacenar/devolver la información relevante de nuestro sistema (módulo Users) o actuar como motor de juego (módulo Rust).
+
A su vez, el módulo Users mantiene una comunicación directa con nuestra base de datos relacional MySQL. La base de datos tiene un volumen asociado para permitir que los datos de nuestro sistema persistan una vez se despliegue el mismo.   

Características de calidad/rendimiento::

El hecho de emplear Docker para encapsular cada uno de los módulos del sistema en distintos contenedores permite que el sistema sea escalable y portable. Además, la separación de las distintas partes en distintos contenedores
facilita el mantenimiento y la extensibilidad. Además, aumenta el rendimiento en comparación con emplear un contendor aislado, ya que se permite aislar las dependencias de cada módulo. Por otro lado, el uso de Docker permite el despliegue
continuo de nuestra aplicación.
+
El despliegue automático desde GitHub Actions favorece tiempos de entrega cortos (en comparación al empleo de otras tecnologías) y una actualización uniforme de los servicios desplegados.

Mapeo de los bloques de construcción a infraestructura::

[cols="1,2" options="header"]
|===

| **Nombre** | **Descripción**

| Azure VM (Linux Ubuntu 24.04) | Máquina virtual que actúa como servidor de la aplicación y sobre la que se despliega toda la infraestructura del sistema.

| Docker | Entorno de ejecución que aísla cada módulo del sistema en distintos contenedores.

| WebApp | Front-end desarrollado en React que permite la interación con el usuario y se comunica directamente con los back-ends del sistema a través de sus correspondientes API REST.

| Users | Back-end desarrollado en Node.js para gestionar la información relevante del sistema (información del usuario, resultado de partidas, ...) y que interactua con la base de datos del sistema.

| Gamey | Back-end Rust que actúa como motor de juego y expone una API REST.

| Database | Base de datos MySQL que almacena la información de valor de la app (usuarios, resultados, ...)

|===


ifdef::arc42help[]
[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****
endif::arc42help[]

=== Nivel de infraestructura 2

[plantuml,"Nivel de infraestructura 2",png]
----
@startuml
skinparam monochrome true
left to right direction

node "Navegador" <<device>> as Navegador

node "Azure VM (Linux Ubuntu 24.04)" <<device>> as AzureVM {

    node "Docker" <<execution environment>> as Docker {
        artifact "WebApp\n(React Front-end)"     as WebApp
        artifact "Users\n(Node Back-end)"        as Users
        artifact "Gamey\n(Rust Game Engine)"     as Gamey
        artifact "Swagger"                       as Swagger

        node "Database" as Database{
            artifact "MySQL"                     as MySQL
            artifact "db_data"                   as Volume <<volume>>
        }
        
        node "Monitoring" as Monitoring{
            artifact "Prometheus"                as Prometheus
            artifact "Grafana"                   as Grafana
        }
    }
}

Navegador   --   WebApp      
WebApp      -->  Users       : <<HTTP/REST>>
WebApp      -->  Gamey       : <<HTTP/REST>>
Users       --   MySQL       
MySQL       --   Volume      : <<mount>>
Prometheus  ..>  Users       
Prometheus  ..>  Gamey       
Grafana     -->  Prometheus  : <<datasource>>
@enduml
----

Descripción::

En este nivel de infraestructura aparecen los módulos destinados a la monitorización del sistema, concretamente, los módulos Grafana y Prometheus.
+
El módulo Prometheus observa constantemente las APIs REST de los back-ends del sistema con el fin de recopilar estadísticas acerca del número de peticiones que reciben cada una de estas en cada instante, el tiempo de respuesta, ...
Todos estos datos se alamcenan en bases de datos volátiles que crea y elimina el propio Prometheus cuando el sistema se sistema se levanta o se tumba respectivamente; por lo tanto, la información no persiste.
+
Por otro lado, el contenedor Grafana accede a los datos extraidos por el módulo Prometheus con el fin de reprensentarlos gráficamente y poder comprender de manera visual el comportamiento de las diferentes APIs del sistema.
+
Además, es necesario mencionar la existencia del contenedor Swagger, destinado a desplegar la documentación sobre las diferentes APIs mencionadas anteriormente: endpoints existentes en cada una, acción asociada a cada uno de estos, URLs, ... 
De esta manera, los desarrollados no tienen que acudir directamente al código (y desperdiciar demasiado tiempo comprendiendo el mismo) para enteder el funcionamiento de las mismas y los distintos servicios que ofrecen.

Características de calidad/rendimiento::

La presencia de Prometheus y Grafana añade observabilidad al entorno, permitiendo monitorizar el comportamiento de la aplicación y detectar incidencias de forma más rápida.
+
Por otro lado, la inclusión de Swagger centraliza la documentación de las APIs de Users y Gamey, reduciendo la fricción durante el desarrollo y facilitando la incorporación de nuevos miembros al equipo. Además permite liberar a las APIS que tienen los servicios de la carga de mostrar la documentación, mejorando el rendimiento.

Mapeo de los bloques de construcción a infraestructura::

[cols="1,2" options="header"]
|===

| **Nombre** | **Descripción**

| Prometheus | Herramienta de monitorización que recopila métricas de los servicios de la aplicación y los almacena en bases de datos temporales.

| Grafana | Herramienta de visualización que consume Prometheus como datasource para mostrar dashboards con las métricas del sistema.

| Swagger | Contenedor destinado a mostrar la documentación asociada a cada una de las APIs del sistema (Users y Gamey).

|===

