ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Diagrama de despliegue

ifdef::arc42help[]
[role="arc42help"]
****
.Content
The deployment view describes:

 1. technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document a deployment view if your software is executed as distributed system with more than one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture only those elements of an infrastructure that are needed to show a deployment of your building blocks. Hardware architects can go beyond that and describe an infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence a system and/or some
cross-cutting concepts. Therefore, there is a need to know the infrastructure.

.Form

Maybe a highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section one can
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than a deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.


.Further Information

See https://docs.arc42.org/section-7/[Deployment View] in the arc42 documentation.

****
endif::arc42help[]

=== Nivel de infraestructura 1

ifdef::arc42help[]
[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****
endif::arc42help[]

[plantuml,"Diagrama de despliegue",png]
----
@startuml
skinparam monochrome true
left to right direction

actor Usuario

node "Azure VM (Linux Ubuntu 24.04)" {

    node "Docker" {

        node "WebApp\n(React Front-end)" as WebApp
        
        node "Users\n(Node Back-end)" as Users
        
        node "Gamey\n(Rust Game Engine)" as Gamey
        
        node "Database" as Database
    }
}

Usuario <--> WebApp : Interacción UI

WebApp <--> Users : HTTP/JSON

Users <--> Gamey : Lógica juego / Bot

Users <--> Database : Persistencia datos
@enduml
----

Motivation::

La aplicación se despliega sobre un servidor de Azure, en el que cada módulo que constituye el sistema se encuentra encapsulado en un contenedor de Docker. El usuario interactua con el sistema a través de una interfaz diseñada con React. Está se comunica con el back-end mediante OpenApi. A su vez, el back-end se comunica con la base de datos con la api mencionada anteriormente.
El back-end también se comunica con el módulo de juego mediante el módulo Rust Bot-server.

Características de calidad/rendimiento::

El hecho de emplear Docker para encapsular cada uno de los módulos del sistema en distintos contenedores permite que el sistema sea escalable y portable. Además, la separación de las distintas partes en distintos contenedores
facilita el mantenimiento y la extensibilidad. Además,  aumenta el rendimiento en comparación con emplear un contendor aislado, ya que se permite aislar las dependencias de cada módulo. Por otro lado, el uso de Docker permite el despliegue
continuo de nuestra aplicación.

Mapeo de los bloques de construcción a infraestructura::

[cols="1,2" options="header"]
|===

| **Nombre** | **Descripción**

| Azure | Servicio con el servidor en el que se encuentra la aplicación.

| Docker | Genera cada uno de los contenedores para almacenar cada uno de los módulos de la aplicación.

| WebApp | Front-end diseñado con React para la interacción con el usuario.

| Users | Back-end diseñado con Node para gestionar la lógica de la aplicación. 

| Gamey | Módulo Rust con la lógica del juego y del bot.

| Database | Almacena un registro de los usuarios de la aplicación, las partidas realizadas, los usuarios obtenidos, ...

|===


ifdef::arc42help[]
[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****
endif::arc42help[]
